version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        links:
                - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mvertes/alpine-mongo
        container_name: mongodb
        ports:
          - "27017:27017"
        volumes:
          - ./data/db:/data/db
